title: Hongru's Homepage
page-top-title: Hongru Wu
top-section-bg-text: Be what you wanna be
home-subtitle: Yourname&ensp;|&ensp;Hongru Wu
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
